### ISSUE TITLE
Is this supporting the android/ios mobile builds

### ISSUE THREAD

**Issue by kahlery** [evanlindsey/Unity-WebGL-SignalR#10]
i have seen an issue about this in another repo written: it is (signalR client) working on editor but when I am playing the game on my mobile phone that I had built with apk it is not working and giving an error about plugins.

So have you ever tried it is it working on mobile builds

**Comment by glebov21** [comment]
> i have seen an issue about this in another repo written: it is (signalR client) working on editor but when I am playing the game on my mobile phone that I had built with apk it is not working and giving an error about plugins.
> 
> So have you ever tried it is it working on mobile builds

Hello. Do you was try this on mobile?

**Comment by evanlindsey** [comment]
Thanks for raising the question. This plugin does not support mobile. In fact, it has [conditional compilation](https://docs.unity3d.com/Manual/PlatformDependentCompilation.html) to throw an error if the target platform is not the Editor or WebGL: [#error PLATFORM NOT SUPPORTED](https://github.com/evanlindsey/Unity-WebGL-SignalR/blob/main/Unity/Assets/Plugins/SignalR/SignalR.cs#L370)
