### ISSUE TITLE
Is it possible to use a contract with more than one type?

### ISSUE THREAD

**Issue by WebMat1** [evanlindsey/Unity-WebGL-SignalR#3]
First of all, you have done a nice work, congratulations...

Is it possible to use a contract with more than one type?

For example on HubConnection (SignalRCore client C#), you can use a contract like
 
hubconnection.ON<type1, type2, type3>( (param 1, param2, param3) => {});

How is the best way to consume this with your package?
Ps.: I notice that you receive all parameters inside e.Payload...

**Comment by evanlindsey** [comment]
@WebMat1 Thanks for the kind words!

For multiple types, there are some limitations when communicating with WebAssembly through emscripten. I outline them in this issue: https://github.com/evanlindsey/Unity-WebGL-SignalR/issues/1

I was able to implement registering multiple method names for the 'on' handlers (using AddHandler) following this issue: https://github.com/evanlindsey/Unity-WebGL-SignalR/issues/2

You are correct, both the target method name (handler) and String payload are returned as HandlerEventArgs in the HandlerInvoked callback. To send or consume multiple arguments, my current suggestion would be to use the payload for JSON: https://github.com/evanlindsey/Unity-WebGL-SignalR#arguments

The lib could be extended to support registering multiple arguments for a handler, but would need matching methods in both the C# and JS classes for each additional one. I don't currently have a solution for doing this dynamically.

**Comment by WebMat1** [comment]
I did some Class to connect to your class and Cast all types Generically to custom Classes...

Can i Pull request this code?

Thank you...

Ps.: Example

```
public static void On<T1>(this SignalRInterface signalR,string methodName, Action<T1> handler)
{
    signalR.Functions.TryAdd(methodName, args => handler(args[0].ToObject<T1>()));
    signalR.AddHandler(methodName);
}
```


```
public static void On<T1, T2>(this SignalRInterface signalR, string methodName, Action<T1, T2> handler)
{
    signalR.Functions.TryAdd(methodName, args => handler(args[0].ToObject<T1>(), args[1].ToObject<T2>()));
    signalR.AddHandler(methodName);
}
```

**Comment by evanlindsey** [comment]
@WebMat1 Sure, PRs are definitely welcome...

However, using generic types in C# isn't really the issue. We need to be sure these methods translate to the .jslib file and can interact through emscripten. This is where the actions take place when using WebGL. Reference:
https://docs.unity3d.com/Manual/webgl-interactingwithbrowserscripting.html

Have a look at this file:
https://github.com/evanlindsey/Unity-WebGL-SignalR/blob/master/Unity/Assets/Plugins/SignalR/SignalRLib.jslib
...and everything below this line:
https://github.com/evanlindsey/Unity-WebGL-SignalR/blob/deff0bef9c475bae1b4fc8d1e005dc32d5d55eb4/Unity/Assets/Plugins/SignalR/SignalRLib.cs#L76

**Comment by WebMat1** [comment]
Yeah, I'm transporting all data by strings, which is supported by emscripten.
So I did a convertion of c# types to strings, and then use your library to send to server and receive from server a object array, which each position will be converted to custom Class back.

Im trying to push my code in a different branch... one second...
Thanks...

**Comment by evanlindsey** [comment]
@WebMat1 Great, looking forward to seeing the changes. I see that you already forked the repo. You should be able to commit to this fork and raise your PR from there: https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork

**Comment by WebMat1** [comment]
Nice... Im doing this right now... Lets see if you like my improvements...

@evanlindsey  https://github.com/evanlindsey/Unity-WebGL-SignalR/pull/4
