### ISSUE TITLE
netstandard 2.1 support for your script

### ISSUE THREAD

**Issue by WillEastbury** [evanlindsey/Unity-WebGL-SignalR#9]
https://github.com/evanlindsey/Unity-WebGL-SignalR/blob/1b87bf0b2710a43b50c2a3f6a4b58cc5bd23395e/Unity/Assets/Plugins/SignalR/lib/signalr.ps1#L3

Hi Evan, great work! 

I've borrowed a little snippet of code from your script and wanted to give you a heads up as I put together a similar sample you might find interesting. I do credit you on the readme.md as well.

https://github.com/WillEastbury/NetStandardSignalRShim/blob/main/FindDeploymentDependenciesSampleScript/depsfilter/downloaddeps.ps1

Only difference is the new version takes netstandard2.1 so works in later editions of unity.

**Comment by evanlindsey** [comment]
@WillEastbury Thanks for sharing your script and referencing mine as the source. This response is way after the fact but I'm glad that you found it useful. I still have this repo set with 2.0 as the target and it has continued to work, even after a recent update to all project dependencies. Yours is a nice example of how it could, in fact, target a higher version. Cheers!
